### ISSUE TITLE
add support for wayfire logout,reboot to uefi,suspend then hibernate

### ISSUE THREAD

**Issue by shrinivas17081997** [ArtsyMacaw/wlogout#1]
wayfire can be logged out
by
ydotool key ctrl + alt + backspace
or
killall wayfire

or
pkill -u $USER
also add
support for

reboot to uefi

suspend then hibernate

**Comment by ArtsyMacaw** [comment]
The default layout file is not meant to be a comprehensive collection of buttons. If you would like to make your own copy the layout file to `~/.config/wlogout/` and add any custom buttons to that for example to create the described buttons:
```
{
    "label" : "uefi",
    "action" : "systemctl reboot --firmware-setup"
    "text" : "Reboot into UEFI"
    "keybind" : "e"
}
{
    "label" : "suspendhibernate",
    "action" : "systemctl suspend-then-hibernate"
    "text" : "Suspend then Hibernate"
    "keybind" : "h"
}
```
And then add an image via style.css

However, the logout command is too specific too sway so I changed it to logout via [logind](https://github.com/ArtsyMacaw/wlogout/releases/tag/1.0.3)
