### ISSUE TITLE
The logout command kills everything

### ISSUE THREAD

**Issue by alexherbo2** [ArtsyMacaw/wlogout#17]
If I start a program, such as [tmux] or a background program, it gets killed at logout.  It does not happen when using `swaymsg exit`.

[tmux]: https://github.com/tmux/tmux

**Comment by dron1885** [comment]
Copy layout to the user folder `cp /etc/wlogout/layout ~/.config/wlogout/` (or modify oroginal) and change logout action to `"action" : "swaymsg exit"`

**Comment by Alucard2169** [comment]
@dron1885  unfortunately, this didn't work for me, so i  just replace the action with `kill -9 -1`, as I have this implemented in my awesome config

**Comment by ArtsyMacaw** [comment]
This is controlled by `KillUserProcesses=` in `logind.conf` and can be switched off
