### ISSUE TITLE
Transparency doesn't work

### ISSUE THREAD

**Issue by zsolt-donca** [ArtsyMacaw/wlogout#18]
The background of the logout menu is not transparent for me, as I think it's supposed to be based on the demo image in the README and on the below setting in the default `style.css`:
```css
window {
	background-color: rgba(12, 12, 12, 0.9);
}
```

I tried copying it to `~/.config/wlogout` and changing the above config, and no matter what I set to alpha, it's still not transparent. However, if I change the RGB components, then the color changes, so my changes take effect.

This is how it looks like with the default style:
![image](https://user-images.githubusercontent.com/6824167/104069987-85a2f080-520e-11eb-9a73-38c46a7d9d79.png)

I am on Arch Linux, and tried with both [wlogout](https://aur.archlinux.org/packages/wlogout/) and [wlogout-git](https://aur.archlinux.org/packages/wlogout-git/) from AUR. I am running a recent development build of sway and wlroots, in case that's relevant.

**Comment by IcyFlamingArrow** [comment]
The buttons can be set individually to a degree of transparency by `opacity: (0.0-1.0)` .
Though the background image for Wlogout is separate from the desktop one and must be configured manually by: (One set by Nitrogen, Variety, or manually) `window {
background-image: image(url("directory/to/image"),
url("directory/to/image"));
}`
With the `directory/to/image` the only syntax you change

You can reduce the amount of typing with `pwd` and paste the result and sequentially typing the file name following the pasted directory.

**Comment by RicArch97** [comment]
How could one achieve what is done in the example image in this repository?

Only thing i can think of using this approach, is:
1. Create a screenshot using, for example, grim of current screen state when pressing the exit keys
2. Use this screenshot as background in wlogout

You'd probably have to use a temp folder somewhere, with the screenshot being removed after you exit wlogout

**Comment by zsolt-donca** [comment]
I can confirm that it indeed works with `-p layer-shell`. Updating the README could be useful for others who might be looking for this as well.

**Comment by Sch00ner** [comment]
Executing with 'wlogout -p layer-shell' works as stated by @RicArch97. It should be added to the README.

**Comment by RicArch97** [comment]
The protocol usage is described in the man page, which is referred to in the README. 

You can run `man wlogout` for the launch options and `man 5 wlogout` for the layout file.

I think this issue can be closed.
