### ISSUE TITLE
cant use wlogout 

### ISSUE THREAD

**Issue by librewish** [ArtsyMacaw/wlogout#2]
~ >>> wlogout                                                                  
Gdk-Message: 23:11:39.036: Error 71 (Protocol error) dispatching to Wayland display.

**Comment by ArtsyMacaw** [comment]
Please run `WAYLAND_DEBUG=1 wlogout 2> ~/log` and post the log file; also please linclude what your DE/wm and distro are.

**Comment by librewish** [comment]
[log.txt](https://github.com/ArtsyMacaw/wlogout/files/4048958/log.txt)

DE/WM - wayfire
distro - manjaro based wayfire linux
https://forum.manjaro.org/t/wayfire-linux-manjaro-spin-with-wayfirewm-3d-wayland-compositer/110398?u=librewish

**Comment by ArtsyMacaw** [comment]
This seems to be a wayfire bug as it never sends a `send_configure` to wlogout; could you please run wlogout on another window manager such as `sway` to see if you can reproduce the issue?

**Comment by psstoyanov** [comment]
I can observe the same. Wlogout doesn't work with Wayfire but works fine under Sway (it did open on KDE as well). Same error as OP.

OS: Manjaro ARM | Device: Pinebook Pro
Wayfire packages:
```
pacman -Qs wayfire
local/wayfire-git r1178.b196fdc-1
    3D wayland compositor
local/wcm-git r121.5ae2ad7-1
    Wayfire Config Manager
local/wf-config-git r50.e8d57d1-1
    A library for managing configuration files, written for wayfire
local/wf-shell-git r125.b240566-1
    GTK3-based panel for the Wayfire compositor
```

**Comment by psstoyanov** [comment]
Where should Wayfire be sending `send_configure` ? I have no idea about the tech involved here, just wondering if I can prod at it if given some pointer 😄

**Comment by ArtsyMacaw** [comment]
@psstoyanov could you try reproducing the issue in Wayfire on `1.0.4` that was just released?

**Comment by psstoyanov** [comment]
Just tried `1.0.4` - no more error and the menu is shown as expected! Thanks, @ArtsyMacaw !

The quick check on the functionality:

-  lock doesn't work (tries to find swaylock. Need to consult your documentation in case that is tucked somewhere in config file somewhere before openign a ticket)
-  I can't check sleep and hybernate on the PBP (work in progress for mainline kernels for the device itself)
-  logout looks like properly killing the session and restarts + power off work as expected.

Awesome work!
