### ISSUE TITLE
Request: Close wlogout when clicking on background

### ISSUE THREAD

**Issue by chron-isch** [ArtsyMacaw/wlogout#21]
Hi, thank you for the work, wlogout has been quite useful on my tablet.
But currently I have to dedicate a button to closing wlogout, since I have no way of hitting `Esc` in tablet mode.

Would it be possible to close wlogout when clicking the background/simply clicking somewhere that isn't a button?

Thanks

**Comment by ArtsyMacaw** [comment]
Fixed in #37
