### ISSUE TITLE
available in arch without the aur

### ISSUE THREAD

**Issue by ura43** [ArtsyMacaw/wlogout#23]
wlogout is available in the arch community repository, meaning it can be installed running `sudo pacman -S wlogout`

**Comment by lokesh-krishna** [comment]
Is this a request to add it to the community repo? It's not in it yet and your wording makes it sound like it is.

**Comment by ura43** [comment]
But it is? Or maybe thats added in by the manjaro maintainers. I'll report back

**Comment by lokesh-krishna** [comment]
Searching for it in [Arch Linux Packages](https://archlinux.org/packages/?sort=&q=wlogout&maintainer=&flagged=) doesn't turn anything up.

**Comment by psstoyanov** [comment]
It is added to the [Manjaro ARM](https://gitlab.manjaro.org/manjaro-arm/packages/community/wayfire/wayfire) repo. Works quite well on SBCs :slightly_smiling_face: 
Haven't seen it in the x86_64 repos of Arch or Manjaro thus far.
