### ISSUE TITLE
Add more specific gtk-layer-shell namespace name

### ISSUE THREAD

**Issue by gekoke** [ArtsyMacaw/wlogout#32]
Here is the output of running `hyprctl layers` (a Hyprland CLI utility) when wlogout is open:
```
Monitor HDMI-A-1:
	Layer level 0 (background):
		Layer 3929af0: xywh: 0 0 1920 1080, namespace: swww
	Layer level 1 (bottom):
	Layer level 2 (top):
		Layer 6212f10: xywh: 0 0 1920 35, namespace: waybar
	Layer level 3 (overlay):
		Layer 6d439b0: xywh: 0 0 1920 1080, namespace: gtk-layer-shell
```
The last entry is wlogout. The namespace value should read something like `wlogout`, so that compositors can apply specific configurations to specific layers. Currently, this value will likely conflict with other programs.

**Comment by latipun7** [comment]
Case closed with https://github.com/ArtsyMacaw/wlogout/pull/30 merged.
