### ISSUE TITLE
Install from yay failed - #3 fix doesn't work

### ISSUE THREAD

**Issue by mostwise** [ArtsyMacaw/wlogout#35]
I am getting the exact same error as #3, but when I type the `gpg --keyserver pgp.mit.edu --recv-keys E25D679AF73CF6D2F` I get an error: `gpg: keyserver recieve failed: Server indicated a failure`, please help.

**Comment by maulik13** [comment]
Not sure if you figured this out, but this has to do it with how gpg resolves the server. I had to add a standard Google nameserver and it worked. I also added  `standard-resolver` to the `~/.gnupg/dirmngr.conf ` file.
