### ISSUE TITLE
marked out of date: wlogout

### ISSUE THREAD

**Issue by Souvlaki42** [ArtsyMacaw/wlogout#41]
Paru notified me today that this package was flagged as [out of date](https://aur.archlinux.org/pkgbase/wlogout/flag-comment) in the AUR (2024-02-05) for the following reason:
`
PGP key cannot be fetched from anywhere. Also needs build changes due to: "WARNING: Running the setup command as 'meson [options]' instead of 'meson setup [options]' is ambiguous and deprecated.".
`
Also according to an AUR comment:
`
Wonder how systemd ended in optional dependencies if it's part of Arch distro itself.
It can be safely removed from optdepends.
`
Do you plan on fixing those issues? Thanks.

**Comment by eljejer** [comment]
same here...

**Comment by ArtsyMacaw** [comment]
The meson and systemd issue have been fixed, however the [PGP](https://keys.openpgp.org/search?q=collinshaden%40gmail.com) key has been [available](https://keyserver.ubuntu.com/pks/lookup?search=F4FDB18A9937358364B276E9E25D679AF73C6D2F&fingerprint=on&op=index) everywhere for [years](https://pgp.mit.edu/pks/lookup?search=collinshaden%40gmail.com&op=index)
