### ISSUE TITLE
wlogout on active monitor

### ISSUE THREAD

**Issue by des1-gner** [ArtsyMacaw/wlogout#43]
Hey there thanks for the update! 

However, I'm now experiencing that my wlogout doesn't launch on my active monitor anymore. 

Any ideas on how to fix this issue?

note that running wlogout with the xdg protocol does launch onto the correct monitor, but refuses to quit, and just gets me stuck on my desktop background.

Running Hyprland

**Comment by des1-gner** [comment]
note that running wlogout with the xdg protocol does launch onto the correct monitor, but refuses to quit, and just gets me stuck on my desktop background. 

Running Hyprland

**Comment by ArtsyMacaw** [comment]
Yeah, an option to launch wlogout on the active monitor is something I need to add; I’ll probably release a patch in a few days. Leaving this issue open till then.

**Comment by bradrn** [comment]
> I’ll probably release a patch in a few days.

That would be great, thanks! I’m also finding this a little annoying.

**Comment by danielwerg** [comment]
In my case I had to add `--primary-monitor 1` flag to fix it.

**Comment by ArtsyMacaw** [comment]
@des1-gner Can you build from the latest commit and see if that fixes your issue?

**Comment by des1-gner** [comment]
> @des1-gner Can you build from the latest commit and see if that fixes your issue?

Seems to work perfectly! Thank you Artsy :)
