### ISSUE TITLE
the logout-dialog layer remains visible on the second screen after wlogout does what it needs to

### ISSUE THREAD

**Issue by alba4k** [ArtsyMacaw/wlogout#45]
This is what hyprlock leaves behind after calling hyprlock.
![immagine](https://github.com/ArtsyMacaw/wlogout/assets/84153269/f2423fb6-0b4c-40d9-b1d4-3d375a4269b5)

It disappears after a while / after random inputs / idk

I am on Hyprland, in case that's relevant, and my configuration can be found [here](https://github.com/alba4k/.dotfiles/tree/master/.config/wlogout)

This is what my config looks like, for reference
![immagine](https://github.com/ArtsyMacaw/wlogout/assets/84153269/2a900026-b191-4106-b0d2-a22e9772aa1e)

This affects 1.2 and 1.2.1

**Comment by ArtsyMacaw** [comment]
@alba4k Can you build from the latest commit and see if that fixes your issue?

**Comment by alba4k** [comment]
fixed, thanks!
