### ISSUE TITLE
Suspend does not lock

### ISSUE THREAD

**Issue by hanckmann** [ArtsyMacaw/wlogout#46]
➜ wlogout --version
1.1.1

Using wlogout on Hyprland on NixOs.

When start wlogout and click the Suspend button, then I expect  two things:

1. the laptop to suspend (sleep),
2. the laptop to be locked on wake-up.

However, when I suspend via wlogout, the laptop goes to sleep but does not ask for a password/fingerprint after waking up.

**Comment by ArtsyMacaw** [comment]
You need to use something like [hypridle](https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/) to make your laptop lock on suspend; wlogout just tells the system to suspend, it doesn’t handle what the environment does after that.
