### ISSUE TITLE
Menu sizing

### ISSUE THREAD

**Issue by clanktron** [ArtsyMacaw/wlogout#51]
Is there any way to change the size of the menu or the individual items? I've tried setting width/height/etc on the window or button classes but any size attributes seem to just break wlogout.

**Comment by ArtsyMacaw** [comment]
the `--margin` and `--column/row-spacing` cli options control the size of the menu in relation to the window

**Comment by voobscout** [comment]
it'd be very nice, if we could specify margins as percentage and not pixels, just to make the menu look the same on any resolution.

perhaps something like this?

```cpp
#include <gtk/gtk.h>

static void set_proportional_margins(GtkWidget *widget, double margin_ratio) {
    GdkScreen *screen = gdk_screen_get_default();
    gint screen_width = gdk_screen_get_width(screen);
    gint screen_height = gdk_screen_get_height(screen);

    gint margin = (gint)(margin_ratio * ((screen_width < screen_height) ? screen_width : screen_height));

    gtk_widget_set_margin_top(widget, margin);
    gtk_widget_set_margin_bottom(widget, margin);
    gtk_widget_set_margin_start(widget, margin);
    gtk_widget_set_margin_end(widget, margin);
}

int main(int argc, char *argv[]) {
    gtk_init(&argc, &argv);

    GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    GtkWidget *box = gtk_box_new(GTK_ORIENTATION_VERTICAL, 0);
    gtk_container_add(GTK_CONTAINER(window), box);

    // Set proportional margins, e.g., 10% of the smaller screen dimension
    set_proportional_margins(box, 0.1);

    gtk_widget_show_all(window);
    gtk_main();

    return 0;
}
```

**Comment by MrHaroldA** [comment]
I would much rather specify how big the menu is instead of specifying in pixels how much margin needs to be around it. My laptop screen also has a different ratio than my external screen.
