### ISSUE TITLE
action cant execute script?

### ISSUE THREAD

**Issue by SuchWowEl** [ArtsyMacaw/wlogout#55]
Hello so I was trying to create a script that shuts my system down gracefully, but when I first tried triggering a script that sends a notification through `wlogout`, nothing came out. When i copy-pasted the command to the action value, the notification showed up. This is also the case for other commands. Is there a workaround for this?

**Comment by ArtsyMacaw** [comment]
There's a lot of different things that could stop it from working. Did you set the script to be executable with `chmod +x'? Is the script in your $PATH or are you specifying the full file path? Try running wlogout from the cli and selecting the script. What does it output? Also try running the script independent of wlogout just from the cli and see if it works there.

**Comment by SuchWowEl** [comment]
as it turned out i forgot to specify the file path, thanks man
