### ISSUE TITLE
[Bug] Swaylock does not work with wlogout

### ISSUE THREAD

**Issue by Heus-Sueh** [ArtsyMacaw/wlogout#62]
Confirming that the swaylock is installed correctly:
```bash
which swaylock
/usr/bin/swaylock
```
even calling swaylock by the full path does not solve the problem
```
{
  "label" : "shutdown",
  "action" : "systemctl poweroff",
  "text" : "Shutdown",
  "keybind" : "s"
},
{
  "label" : "reboot",
  "action" : "systemctl reboot",
  "text" : "Reboot",
  "keybind" : "r"
},
{
  "label" : "logout",
  "action" : "loginctl terminate-session $XDG_SESSION_ID",
  "text" : "Logout",
  "keybind" : "e"
},
{
  "label" : "hibernate",
  "action" : "swaylock -f && systemctl hibernate",
  "text" : "Hibernate",
  "keybind" : "h"
},
{
  "label" : "lock",
  "action" : "/usr/bin/swaylock",
  "text" : "Lock",
  "keybind" : "l"
}
```

System Info:

```bash
# cat /etc/os-release
NAME="Fedora Linux"
VERSION="40.20240820.0 (Sway Atomic)"
```

**Comment by hungry-bogart** [comment]
My config is almost the same as yours, but I can lock the screen just fine. I'm also on Sway. 

```
...
{
    "label" : "lock",
    "action" : "swaylock",
    "text" : "Lock",
    "keybind" : "l"
}
...
```

I've omitted the rest of the config to focus on the lock section. So, you should see that I simply entered Swaylock with no arguments.

Once it locks the screen, it goes to a strange white page with a circle in the center. I don't know if that's what it's supposed to do, but after I enter my password it lets me back into the session.

**Comment by hungry-bogart** [comment]
I also can only get to a black screen with the same logout settings as your config. Let me know if you were able to get that to work.

**Comment by Heus-Sueh** [comment]
Unfortunately I can't test it anymore because I switched to Hyprland, maybe something external was preventing the swaylock from opening, for now I'm going to close this issue since there's no way to track this "bug"
