### ISSUE TITLE
available in fedora

### ISSUE THREAD

**Issue by bhepple** [ArtsyMacaw/wlogout#8]
You might want to mention that this package is now available for Fedora users. eg see https://www.reddit.com/r/Fedora/comments/fjhhp7/fedora_package_for_wlogout111_is_available/

Instructions are at: https://copr.fedorainfracloud.org/coprs/wef/wlogout/builds/ but boil down to:

```
sudo dnf copr enable wef/wlogout
sudo dnf install wlogout
```

**Comment by pinkman7009** [comment]
Is this package available for Ubuntu users?

**Comment by bhepple** [comment]
I have no idea - I just work with Fedora.

**Comment by ArtsyMacaw** [comment]
Fixed
